import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { APP_NAME } from '@/constants'
import Container from '@mui/material/Container'
import Topbar from '@/components/layout/Topbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <Topbar />
        <Container maxWidth="xl" sx={{ py: 10 }}>
          {children}
        </Container>
      </body>
    </html>
  )
}

export default RootLayout
